apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - general
patches:
  - path: patches/patch.yaml
    target:
      kind: ConfigMap
      annotationSelector: "test-annotation=kustomize"
